openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation for Contacts App
tags:
  - name: Contacts
    description: operations with contacts.
  - name: Auth
    description: Authorizations operations.
  # теги, що ви будете використовувати
servers:
  - url: http://127.0.0.1:3000
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
  /contacts:
    post:
      $ref: ../swagger/paths/contacts/post.yaml
    get:
      $ref: ../swagger/paths/contacts/get.yaml
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
